param([switch]$Render, [switch]$CardOnly, [switch]$CompileOnly, [switch]$Due, [switch]$Frame, [switch]$Place, [switch]$CalendarStyle, [switch]$Fold, [switch]$InlineEdit, [switch]$Language, [switch]$English, [switch]$Deadline, [switch]$Taskbar, [switch]$Shortcut, [switch]$Outlook, [switch]$AllDay, [string]$Guide = '', [string]$Site = '', [string]$PageTurn = '', [string]$TitleGap = '')
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$compilerPath = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
$artifactPath = Join-Path $projectRoot 'artifacts'
New-Item -ItemType Directory -Force -Path $artifactPath | Out-Null
$testExe = Join-Path $artifactPath 'NotebookLayoutTests.exe'
$sourceFiles = Get-ChildItem -LiteralPath (Join-Path $projectRoot 'src') -Filter '*.cs' | ForEach-Object FullName
$buildArgs = @('/nologo', '/target:exe', '/main:NotebookLayoutTests', '/codepage:65001', ('/out:' + $testExe), ('/win32manifest:' + (Join-Path $projectRoot 'src\app.manifest')), '/reference:System.dll', '/reference:System.Core.dll', '/reference:System.Drawing.dll', '/reference:System.Windows.Forms.dll', '/reference:System.Web.Extensions.dll')
& $compilerPath @buildArgs @sourceFiles (Join-Path $PSScriptRoot 'NotebookLayoutTests.cs') (Join-Path $PSScriptRoot 'ShortcutChecks.cs') (Join-Path $PSScriptRoot 'PlacementChecks.cs') (Join-Path $PSScriptRoot 'CalendarStyleChecks.cs') (Join-Path $PSScriptRoot 'FoldChecks.cs') (Join-Path $PSScriptRoot 'InlineEditChecks.cs') (Join-Path $PSScriptRoot 'LangChecks.cs') (Join-Path $PSScriptRoot 'EnglishChecks.cs') (Join-Path $PSScriptRoot 'DeadlineChecks.cs') (Join-Path $PSScriptRoot 'TitleGapShot.cs') (Join-Path $PSScriptRoot 'TaskbarChecks.cs') (Join-Path $PSScriptRoot 'OutlookChecks.cs') (Join-Path $PSScriptRoot 'PageTurnChecks.cs') (Join-Path $PSScriptRoot 'AllDayChecks.cs') (Join-Path $PSScriptRoot 'GuideShots.cs') (Join-Path $PSScriptRoot 'SiteShots.cs')
if ($LASTEXITCODE -ne 0) { throw 'Notebook layout test compilation failed.' }
if ($CompileOnly) { Write-Output "Compiled: $testExe"; exit 0 }
$dataPath = Join-Path $artifactPath ('layouts-' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
if ($Due) { & $testExe $dataPath due 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-due.log'); if ($LASTEXITCODE -ne 0) { throw 'Notebook deadline picker checks failed.' }; exit 0 }
if ($Frame) { & $testExe $dataPath frame 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-frame.log'); if ($LASTEXITCODE -ne 0) { throw 'Desktop widget mode checks failed.' }; exit 0 }
if ($TitleGap -ne '') { & $testExe $dataPath titlegap $TitleGap 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-titlegap.log'); if ($LASTEXITCODE -ne 0) { throw 'Title gap shot failed.' }; exit 0 }
if ($PageTurn -ne '') { & $testExe $dataPath pageturn $PageTurn 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-pageturn.log'); if ($LASTEXITCODE -ne 0) { throw 'Page turn checks failed.' }; exit 0 }
if ($Site -ne '') { & $testExe ($dataPath + '-' + $Site) ('site-' + $Site) 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath ('layouts-site-' + $Site + '.log')); if ($LASTEXITCODE -ne 0) { throw 'Site screenshots failed.' }; exit 0 }
if ($Guide -ne '') { & $testExe ($dataPath + '-' + $Guide) ('guide-' + $Guide) 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath ('layouts-guide-' + $Guide + '.log')); if ($LASTEXITCODE -ne 0) { throw 'Guide screenshots failed.' }; exit 0 }
if ($AllDay) { & $testExe $dataPath allday 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-allday.log'); if ($LASTEXITCODE -ne 0) { throw 'All-day checks failed.' }; & $testExe $dataPath alldayread 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-alldayread.log'); if ($LASTEXITCODE -ne 0) { throw 'All-day restart check failed.' }; exit 0 }
if ($Outlook) { & $testExe $dataPath outlook 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-outlook.log'); if ($LASTEXITCODE -ne 0) { throw 'Outlook checks failed.' }; & $testExe $dataPath outlookread 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-outlookread.log'); if ($LASTEXITCODE -ne 0) { throw 'Outlook restart check failed.' }; & $testExe $dataPath outlookimport 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-outlookimport.log'); if ($LASTEXITCODE -ne 0) { throw 'Outlook import check failed.' }; exit 0 }
if ($Shortcut) { foreach ($m in 'shortcut', 'shortcutread') { & $testExe $dataPath $m 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath ('layouts-' + $m + '.log')); if ($LASTEXITCODE -ne 0) { throw ('Shortcut checks failed: ' + $m) } }; & $testExe ($dataPath + '-en') 'shortcut-en' 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-shortcut-en.log'); if ($LASTEXITCODE -ne 0) { throw 'English shortcut checks failed.' }; exit 0 }
if ($Taskbar) { & $testExe $dataPath taskbar 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-taskbar.log'); if ($LASTEXITCODE -ne 0) { throw 'Taskbar checks failed.' }; & $testExe $dataPath taskbarread 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-taskbarread.log'); if ($LASTEXITCODE -ne 0) { throw 'Taskbar restart check failed.' }; exit 0 }
if ($Deadline) { & $testExe $dataPath ddl 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-ddl.log'); if ($LASTEXITCODE -ne 0) { throw 'Deadline checks failed.' }; exit 0 }
if ($English) { & $testExe $dataPath english 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-english.log'); if ($LASTEXITCODE -ne 0) { throw 'English checks failed.' }; Write-Output "English screens: $dataPath\english"; exit 0 }
if ($Language) { & $testExe $dataPath lang 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-lang.log'); if ($LASTEXITCODE -ne 0) { throw 'Language checks failed.' }; & $testExe ($dataPath + '-en') langfresh 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-langfresh.log'); if ($LASTEXITCODE -ne 0) { throw 'English first-run check failed.' }; exit 0 }
if ($InlineEdit) { & $testExe $dataPath inline 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-inline.log'); if ($LASTEXITCODE -ne 0) { throw 'Inline edit checks failed.' }; & $testExe $dataPath inlineread 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-inlineread.log'); if ($LASTEXITCODE -ne 0) { throw 'Inline edit restart check failed.' }; exit 0 }
if ($Fold) { & $testExe $dataPath fold 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-fold.log'); if ($LASTEXITCODE -ne 0) { throw 'Fold checks failed.' }; & $testExe $dataPath foldread 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-foldread.log'); if ($LASTEXITCODE -ne 0) { throw 'Fold restart check failed.' }; exit 0 }
if ($CalendarStyle) { & $testExe $dataPath calstyle 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-calstyle.log'); if ($LASTEXITCODE -ne 0) { throw 'Calendar style checks failed.' }; & $testExe $dataPath calstyleread 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-calstyleread.log'); if ($LASTEXITCODE -ne 0) { throw 'Calendar style restart check failed.' }; exit 0 }
if ($Place) { & $testExe $dataPath place 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-place.log'); if ($LASTEXITCODE -ne 0) { throw 'Widget placement checks failed.' }; & $testExe $dataPath placeread 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-placeread.log'); if ($LASTEXITCODE -ne 0) { throw 'Widget placement restart check failed.' }; exit 0 }
if ($Render) { & $testExe $dataPath render 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-render.log'); if ($LASTEXITCODE -ne 0) { throw 'Notebook layout rendering failed.' }; exit 0 }
if ($CardOnly) { & $testExe $dataPath card 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-card.log'); if ($LASTEXITCODE -ne 0) { throw 'Notebook card stage failed.' }; exit 0 }
& $testExe $dataPath write 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-write.log')
if ($LASTEXITCODE -ne 0) { throw 'Notebook layout write phase failed.' }
& $testExe $dataPath read 2>&1 | Tee-Object -FilePath (Join-Path $artifactPath 'layouts-read.log')
if ($LASTEXITCODE -ne 0) { throw 'Notebook layout restart phase failed.' }
Write-Output "Notebook layout data: $dataPath"
