using System.Collections.Generic;

namespace DeskStudy
{
    // English interface text, keyed by the Chinese original. Anything missing here shows in Chinese.
    public static partial class Lang
    {
        static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            // Language card in the settings center (the card itself is always bilingual).
            { "界面语言 · Language", "Language · 界面语言" },
            { "界面语言", "Language" },
            { "切换语言后需要重启程序 · Restart DeskStudy to apply", "Restart DeskStudy to apply · 切换语言后需要重启程序" },
            { "立即重启 · Restart now", "Restart now · 立即重启" },
            { "重启后切换为所选语言 · The new language applies after a restart", "The new language applies after a restart · 重启后切换为所选语言" },
            // Interface text.
            { "日历 · 课表", "Calendar" },
            { "今天", "Today" },
            { " 今天", " Today" },
            { "工作周", "Work week" },
            { "周", "Week" },
            { "月", "Month" },
            { "＋ 添加日程", "+ Add event" },
            { "每一天，留一点从容   ·   点击课程编辑；双击空白处添加", "A little calm every day   ·   Click an event to edit; double-click an empty slot to add" },
            { "教学第 {0} 周", "Week {0}" },
            { "点击课程编辑；双击空白处添加", "Click an event to edit; double-click an empty slot to add" },
            { "周一", "Mon" },
            { "周一\n9/28", "Mon\n9/28" },
            { "上一周或上一月", "Previous week or month" },
            { "下一周或下一月", "Next week or month" },
            { "回到今天", "Back to today" },
            { "工作周视图：只看周一至周五", "Work week view: Monday to Friday only" },
            { "周视图", "Week view" },
            { "月视图", "Month view" },
            { "添加日程", "Add event" },
            { "只看周一至周五", "Monday to Friday only" },
            { "本周还没有日程 · 双击时间格开始安排", "Nothing scheduled this week · Double-click a time slot to add an event" },
            { "+ {0} 项 · 查看", "+ {0} more · View" },
            { "全部日程", "All events" },
            { "循环课程", "Recurring event" },
            { "要修改或删除哪一部分？", "Which part do you want to change or delete?" },
            { "“仅这一次”保留其他日期的课程安排。", "\"Only this one\" keeps the event on all other dates." },
            { "仅这一次", "Only this one" },
            { "整个系列", "The whole series" },
            { "取消", "Cancel" },
            { "编辑日程", "Edit event" },
            { "编辑 · 仅这一次", "Edit · only this one" },
            { "名称", "Name" },
            { "yyyy 年 MM 月 dd 日", "yyyy-MM-dd" },
            { "日期 / 起日", "Date / first day" },
            { "至", "to" },
            { "上课时间", "Time" },
            { "地点", "Location" },
            { "备注", "Notes" },
            { "鼠尾草绿", "Sage" },
            { "雾蓝", "Mist blue" },
            { "浅紫", "Lilac" },
            { "杏茶", "Apricot" },
            { "玫瑰", "Rose" },
            { "橄榄", "Olive" },
            { "颜色", "Color" },
            { "不重复", "Does not repeat" },
            { "每周", "Every week" },
            { "每两周", "Every two weeks" },
            { "重复", "Repeat" },
            { "周二", "Tue" },
            { "周三", "Wed" },
            { "周四", "Thu" },
            { "周五", "Fri" },
            { "周六", "Sat" },
            { "周日", "Sun" },
            { "每逢", "On" },
            { "循环截止", "Repeat until" },
            { "双周基准日", "Cycle start" },
            { "勾选：以此日期所在周作为每两周循环的第 1 周。取消勾选：按课程起日所在周循环。已有课程不会跟随全局教学周设置改动。\n要从教学第 2 周上课，请将此日期设为第 2 周内任一天。", "Ticked: the week of this date counts as week 1 of the every-two-weeks cycle. Unticked: the cycle starts from the event's first day. Existing events do not follow changes to the term settings.\nTo start in teaching week 2, pick any day in week 2." },
            { "按本地上课时间循环（含夏令时）。时区：\n", "Keeps the local time (daylight saving aware). Time zone:\n" },
            { "时区", "Time zone" },
            { "保存日程", "Save event" },
            { "删除日程", "Delete event" },
            { "取消这次课程", "Cancel this one" },
            { "确定删除整个循环系列及其例外安排？", "Delete the whole recurring series and its one-off changes?" },
            { "确定删除这次日程？", "Delete this event?" },
            { "删除确认", "Confirm delete" },
            { "请填写日程名称。", "Please enter a name for the event." },
            { "结束时间须晚于开始时间；跨天日程请分成两条。", "The end time must be after the start time; split events that run past midnight into two." },
            { "循环截止日期不能早于开始日期。", "The repeat-until date cannot be before the first day." },
            { "循环跨度不能超过 100 年。", "A series cannot span more than 100 years." },
            { "请至少选择一个重复星期。", "Please choose at least one day of the week." },
            { "折叠", "Fold" },
            { "展开", "Unfold" },
            { "展开，回到原来的位置（双击顶栏也可以）", "Unfold back to where it was (or double-click the header)" },
            { "折叠到屏幕底部（双击顶栏也可以）", "Fold to the bottom of the screen (or double-click the header)" },
            { "隐藏这个组件", "Hide this widget" },
            { "置顶", "Pin" },
            { "打开设置中心", "Open settings" },
            { "隐藏", "Hide" },
            { "便签", "Notebook" },
            { "新的一页", "New page" },
            { "新日程", "New event" },
            { "此时区的时间无法转换。", "This time cannot be converted in this time zone." },
            { "查询日期范围过大。", "The date range is too large." },
            { "所选日期不属于此日程系列。", "The chosen date is not part of this series." },
            { "主数据文件无法读取，已从上一份备份恢复。原文件已保留：{0}。原因：{1}", "The data file could not be read, so the previous copy was restored. The original file was kept: {0}. Reason: {1}" },
            { "无法读取原数据，已保留损坏文件：{0}。当前显示空白数据。原因：{1}", "The data could not be read. The damaged file was kept: {0}. Starting with empty data. Reason: {1}" },
            { "数据已兼容新版设置。更新前的原始数据已保留：{0}", "Your data was updated for this version. A copy from before the update was kept: {0}" },
            { "找不到数据文件。", "The data file cannot be found." },
            { "数据文件超过 32 MB 限制。", "The data file is larger than the 32 MB limit." },
            { "这不是完整的 DeskStudy 备份文件（缺少版本或必要数据字段）。", "This is not a complete DeskStudy backup (the version or required data is missing)." },
            { "不支持此数据版本，请使用兼容的应用版本。原数据保持不变。", "This data version is not supported. Please use a compatible version of the app. Your data was not changed." },
            { "备份中的记录缺少必要字段，未导入。", "Some records in the backup are missing required fields. Nothing was imported." },
            { "备份中的列表格式无效，未导入。", "A list in the backup is not valid. Nothing was imported." },
            { "版本 {0} 备份缺少设置，未导入。", "The version {0} backup has no settings. Nothing was imported." },
            { "组件外观数据无效。", "The widget appearance data is not valid." },
            { "保存的布局数据无效。", "The saved layout data is not valid." },
            { "请选择数据目录以外的备份文件名。", "Please choose a backup file outside the data folder." },
            { "数据超过 32 MB 限制。", "The data is larger than the 32 MB limit." },
            { "{0}为空或过长。", "{0} is empty or too long." },
            { "结束时间必须晚于开始时间（单次日程不跨午夜）。", "The end time must be after the start time (an event cannot run past midnight)." },
            { "颜色应为 #RRGGBB。", "The color must be #RRGGBB." },
            { "日程例外不能为空。", "A one-off change cannot be empty." },
            { "日程名称", "Event name" },
            { "无效的数据文件。", "The data file is not valid." },
            { "不支持此数据版本，请使用兼容的应用版本。", "This data version is not supported. Please use a compatible version of the app." },
            { "日程列表无效或数量过多。", "The event list is not valid or too long." },
            { "数据必须包含 Todo 和 DDL 两本便签。", "The data must contain both notebooks (To-do and Deadlines)." },
            { "窗口信息无效。", "The window information is not valid." },
            { "缺少窗口信息：{0}", "Window information is missing: {0}" },
            { "窗口尺寸或位置无效。", "A window size or position is not valid." },
            { "日程不能为空。", "An event cannot be empty." },
            { "循环周期无效。", "The repeat interval is not valid." },
            { "循环教学周起点", "Cycle start" },
            { "循环星期设置无效。", "The repeat days are not valid." },
            { "循环结束日期早于开始日期。", "The repeat-until date is before the first day." },
            { "取消记录无效。", "A cancelled date is not valid." },
            { "日程例外列表无效。", "The list of one-off changes is not valid." },
            { "同一次日程有重复例外。", "The same occurrence has more than one change." },
            { "便签名称", "Notebook name" },
            { "便签页面列表无效。", "The notebook's page list is not valid." },
            { "当前便签页不存在。", "The current page does not exist." },
            { "页面不能为空。", "A page cannot be empty." },
            { "页面标题", "Page title" },
            { "页面内容", "Page notes" },
            { "任务列表无效。", "The task list is not valid." },
            { "任务数量超过 100000 条限制。", "There are more than 100,000 tasks." },
            { "任务不能为空。", "A task cannot be empty." },
            { "任务内容", "Task text" },
            { "提前提醒时间无效。", "The reminder lead time is not valid." },
            { "截止时间", "Due time" },
            { "仅日期的截止时间缺少日期。", "A date-only deadline has no date." },
            { "提醒状态", "Reminder state" },
            { "提醒历史无效。", "The reminder history is not valid." },
            { "提醒记录不能为空。", "A reminder record cannot be empty." },
            { "提醒 ID", "Reminder ID" },
            { "任务 ID", "Task ID" },
            { "提醒内容", "Reminder text" },
            { "提醒类型无效。", "The reminder type is not valid." },
            { "数据包含重复 ID。", "The data contains duplicate IDs." },
            { "时间格式无效。", "The time format is not valid." },
            { "窗口模式无效。", "The window mode is not valid." },
            { "组件四角样式无效。", "The corner style is not valid." },
            { "设置中的保存时间无效。", "A saved time in the settings is not valid." },
            { "外观设置不能为空。", "The appearance settings cannot be empty." },
            { "自定义外观字段无效。", "The customised appearance fields are not valid." },
            { "主题设置无效。", "The theme is not valid." },
            { "背景颜色应为 #RRGGBB。", "The background color must be #RRGGBB." },
            { "透明度应在 35% 到 100% 之间。", "Opacity must be between 35% and 100%." },
            { "字号应在 8 到 14 之间。", "The font size must be between 8 and 14." },
            { "缺少设置数据。", "The settings are missing." },
            { "便签布局无效。", "The notebook layout is not valid." },
            { "界面语言无效。", "The language is not valid." },
            { "快捷键无效。", "The shortcut is not valid." },
            { "组件外观设置无效。", "The widget appearance settings are not valid." },
            { "未知的组件外观设置。", "Unknown widget appearance setting." },
            { "缺少日历设置。", "The calendar settings are missing." },
            { "默认视图无效。", "The calendar view is not valid." },
            { "每周起始日无效。", "The first day of the week is not valid." },
            { "学期日期范围无效。", "The term dates are not valid." },
            { "缺少提醒设置。", "The reminder settings are missing." },
            { "默认提前时间无效。", "The default reminder lead time is not valid." },
            { "自动保存间隔应在 100 到 10000 毫秒之间。", "The autosave delay must be between 100 and 10,000 ms." },
            { "保存的布局无效。", "The saved layout is not valid." },
            { "保存的布局包含未知组件。", "The saved layout contains an unknown widget." },
            { "保存的窗口尺寸或位置无效。", "A saved window size or position is not valid." },
            { "快捷键需要包含 Ctrl、Alt 或 Win，并以字母、数字或 F1–F12 结尾。", "A shortcut needs Ctrl, Alt or Win and must end with a letter, a digit or F1–F12." },
            { "隔离数据模式下不注册全局快捷键。", "The global shortcut is not registered when running on a separate data folder." },
            { "快捷键已停用。", "The shortcut is turned off." },
            { "快捷键已生效。", "The shortcut is active." },
            { "这个快捷键已被其他程序占用，请换一个。", "Another program already uses this shortcut. Please choose another." },
            { "选择截止日期", "Choose a due date" },
            { "时:分", "HH:MM" },
            { "分钟", "min" },
            { "设置截止时间", "Set a due time" },
            { "明天", "Tomorrow" },
            { "本周五", "This Friday" },
            { "下周五", "Next Friday" },
            { "下周一", "Next Monday" },
            { "上次 {0}", "Last used {0}" },
            { "时间", "Time" },
            { "自定义截止时间，例如 18:30", "Custom due time, e.g. 18:30" },
            { "提醒", "Reminders" },
            { "自定义提前分钟数", "Custom minutes before" },
            { "完成", "Done" },
            { "清除截止时间", "Clear due time" },
            { "到期时", "At due time" },
            { "只选日期：当天 {0} 提醒一次", "Date only: reminder at {0}" },
            { "未选择日期", "No date chosen" },
            { "不设置截止时间", "No due time" },
            { "这个时间已经过了", "this time has passed" },
            { "时间格式应为 18:30", "Use a time like 18:30" },
            { "这个时间处于夏令时跳转区间", "This time falls in a daylight-saving change" },
            { "Enter 完成 · Esc 取消", "Enter to finish · Esc to cancel" },
            { "+ 截止时间", "+ Due time" },
            { "为新任务设置截止时间", "Set a due time for the new task" },
            { "为这项任务设置截止时间", "Set a due time for this task" },
            { "当天 {0} 提醒", "reminder at {0} that day" },
            { "，当前已选中", ", selected" },
            { "，点击选择", ", click to select" },
            { "✓ 已选中", "✓ Selected" },
            { "默认推荐", "Recommended" },
            { "点击使用", "Click to use" },
            { "页面列表", "Pages" },
            { "＋ 新页", "+ New page" },
            { "重命名便签", "Rename notebook" },
            { "文字记录  ▾", "Notes  ▾" },
            { "本页文字记录", "Notes on this page" },
            { "任务", "Tasks" },
            { "＋ 添加任务", "+ Add task" },
            { "隐藏、翻页、归档后仍会提醒", "Reminders continue when hidden, on other pages or archived" },
            { "未命名页", "Untitled page" },
            { "创建于 {0}", "Created {0}" },
            { "文字记录  ▸  （点击展开）", "Notes  ▸  (click to open)" },
            { "任务  {0} / {1} 已完成", "Tasks  {0} / {1} done" },
            { "从下面记下一件要做的事。", "Add something to do below." },
            { "这一页还没有任务\r\n\r\n记下一件小事，完成后也会留在这里。", "No tasks on this page yet\r\n\r\nAdd a small task; it stays here after you finish it." },
            { "完成任务：{0}", "Complete task: {0}" },
            { "编辑", "Edit" },
            { "删除", "Delete" },
            { "上移任务", "Move task up" },
            { "下移任务", "Move task down" },
            { "任务操作", "Task actions" },
            { "已完成", "Done" },
            { "截止 {0}", "due {0}" },
            { "未设置截止时间", "No due time" },
            { "已逾期", "Overdue" },
            { "即将截止", "Due very soon" },
            { "24 小时内截止", "Due within 24 hours" },
            { "待完成", "To do" },
            { "到期提醒", "Reminder at due time" },
            { "提前 {0} 分钟提醒", "Reminder {0} min before" },
            { "删除这项任务？此操作不会影响其他任务。", "Delete this task? Other tasks are not affected." },
            { "删除任务", "Delete task" },
            { "保存", "Save" },
            { "请输入便签名称。", "Please enter a name for the notebook." },
            { "还差一个名称", "A name is needed" },
            { "添加任务", "Add task" },
            { "编辑任务", "Edit task" },
            { "要完成什么？", "What needs doing?" },
            { "设置截止时间与提醒", "Set a due time and reminder" },
            { "只设日期，不设具体时间（当天提醒一次）", "Date only, no time (one reminder that day)" },
            { "提前提醒", "Remind me" },
            { "分钟（0 = 到期提醒）", "min before (0 = at due time)" },
            { "保存任务", "Save task" },
            { "请输入任务内容。", "Please enter the task." },
            { "还差一点内容", "Something is missing" },
            { "此时间处于夏令时跳转区间，请选择一个有效的本地时间。", "This time falls in a daylight-saving change. Please choose a valid local time." },
            { "时间不可用", "Time not available" },
            { "翻到其他页面仍会提醒；完成后停止提醒。\r\n时间使用当前本地时区，提醒在应用运行时生效。", "Reminders work on any page and stop once the task is done.\r\nTimes use your local time zone; DeskStudy must be running." },
            { "编辑任务内容，回车保存，Shift+回车换行，Esc 取消", "Edit the task: Enter to save, Shift+Enter for a new line, Esc to cancel" },
            { "页面目录", "Page list" },
            { "页面详情和便签操作", "Page details and notebook actions" },
            { "纸页目录", "Page tabs" },
            { "添加任务内容，按回车连续录入", "Type a task and press Enter to add more" },
            { "＋ 添加", "+ Add" },
            { "记下一件事，回车添加", "Add a task, press Enter" },
            { " · 截止本", "" },
            { " · 待办本", "" },
            { "+ 新一页", "+ New page" },
            { "添加截止事项…", "Add a deadline…" },
            { "添加一项任务…", "Add a task…" },
            { "页内备注", "Page notes" },
            { "已记录", "has notes" },
            { "有内容", "has notes" },
            { "{0} 项待完成", "{0} to do" },
            { "{0}/{1} 完成", "{0}/{1} done" },
            { "{0} / {1} 已完成", "{0} / {1} done" },
            { "第 {0} / {1} 页", "Page {0} of {1}" },
            { "打开页面", "Open page" },
            { "点击页标题可直接重命名", "Click the page title to rename it" },
            { "重命名便签本…", "Rename notebook…" },
            { "页面目录…", "Page list…" },
            { "设置中心…", "Settings…" },
            { "编辑任务 / 截止时间…", "Edit task / due time…" },
            { "删除任务…", "Delete task…" },
            { "写下这一页的第一件事", "Write the first thing for this page" },
            { "今天截止", "Due today" },
            { "明天截止", "Due tomorrow" },
            { "今天 {0}", "Today {0}" },
            { "明天 {0}", "Tomorrow {0}" },
            { "提前 {0} 分钟", "{0} min before" },
            { "便签名称不能为空。", "The notebook name cannot be empty." },
            { "页面名称不能为空。", "The page name cannot be empty." },
            { "开机启动未应用", "Start at sign-in not applied" },
            { "桌面课笺 · 测试通知", "DeskStudy · Test notification" },
            { "设置中心 · 桌面课笺", "Settings · DeskStudy" },
            { "设置中心", "Settings" },
            { "课表、便签与桌面，都在这里。更改会自动保存。", "Timetable, notebooks and desktop, all in one place. Changes save automatically." },
            { "关闭此窗口后，桌面组件与提醒继续运行。", "Widgets and reminders keep running after you close this window." },
            { "设置页面", "Settings pages" },
            { "组件总览", "Widgets" },
            { "显示与布局", "Display and layout" },
            { "外观", "Appearance" },
            { "日历与课表", "Calendar" },
            { "便签与页面", "Notebooks and pages" },
            { "数据与应用", "Data and app" },
            { "更改已应用并自动保存。关闭设置中心后，组件与提醒继续运行。", "Changes are applied and saved. Widgets and reminders keep running after you close Settings." },
            { "无法完成操作", "Could not complete" },
            { "三个独立窗口，随时显示、隐藏或定位。隐藏窗口后，所有页面中的任务仍会提醒。", "Three separate windows you can show, hide or find at any time. Tasks on every page still remind you while a window is hidden." },
            { "桌面工作区", "Desktop" },
            { "显示全部", "Show all" },
            { "隐藏全部", "Hide all" },
            { "找回当前屏幕", "Bring back to this screen" },
            { "在桌面显示", "Show on desktop" },
            { "快速定位", "Find" },
            { "位置与尺寸使用屏幕像素。锁定位置后，组件不再接受拖动和调整大小；仍可在这里修改。", "Positions and sizes are in screen pixels. A locked widget cannot be dragged or resized, but can still be changed here." },
            { "窗口模式", "Window mode" },
            { "桌面组件模式", "Desktop widgets" },
            { "标准窗口", "Standard windows" },
            { "组件窗口", "Widget windows" },
            { "圆角", "Rounded" },
            { "直角", "Square" },
            { "组件四角", "Corners" },
            { "桌面组件模式下生效。平时没有阴影；拖动或调整大小时显示系统阴影（Windows 11 上此时为系统圆角）。", "Applies to desktop widgets. No shadow at rest; the system shadow shows while dragging or resizing (with the system's rounded corners on Windows 11)." },
            { "桌面组件模式：组件没有标题栏，各自不占任务栏。拖动顶栏移动，拖动边缘调整大小。", "Desktop widgets have no title bar and no taskbar buttons of their own. Drag the header to move, drag an edge to resize." },
            { "点击组件时它浮到前面；切到别的程序后，它自动回到其他窗口下面。勾选「始终置顶」的组件不受影响。", "Clicking a widget brings it to the front; switching to another program sends it back behind. Widgets set to \"Always on top\" stay on top." },
            { "显示或收起全部组件的快捷键，点击后按下新的组合键", "Shortcut to bring all widgets forward or send them back; click, then press a new combination" },
            { "显示 / 收起快捷键", "Show / hide shortcut" },
            { "停用", "Turn off" },
            { "恢复默认", "Default" },
            { "点一下输入框，再按下新的组合键即可修改。按一次把组件浮到前面，再按一次收回去。", "Click the box and press a new combination to change it. Press once to bring the widgets forward, again to send them back." },
            { "单击托盘图标也能把组件浮到前面。", "Clicking the tray icon also brings the widgets forward." },
            { "布局管理", "Layout" },
            { "保存当前布局", "Save layout" },
            { "恢复已保存布局", "Restore saved layout" },
            { "恢复默认布局", "Default layout" },
            { "将组件找回当前屏幕", "Bring widgets to this screen" },
            { "日历", "Calendar" },
            { "Todo 便签", "To-do" },
            { "DDL 便签", "Deadlines" },
            { "宽", "W" },
            { "高", "H" },
            { "窗口位置", "Position" },
            { "窗口尺寸", "Size" },
            { "始终置顶", "Always on top" },
            { "锁定位置与尺寸", "Lock position and size" },
            { "颜色、透明度与字号会实时应用到桌面组件。单个组件可以覆盖全局设置，也可以重新跟随全局。", "Colors, opacity and font size apply to the widgets right away. A widget can have its own settings or follow the global ones." },
            { "中文", "中文" },
            { "便签布局 · Todo 与 DDL 同步切换", "Notebook layout · To-do and Deadlines switch together" },
            { "原始外观", "Original" },
            { "轻量卡片", "Light cards" },
            { "纸页本", "Paper" },
            { "清爽卡片", "Clean cards" },
            { "手账纸页", "Journal" },
            { "顶部翻页，保留文字区与完整操作按钮。", "Page list on top, notes area, all task buttons." },
            { "任务优先，折叠备注，固定底部翻页。", "Tasks first, folding notes, pages at the bottom." },
            { "暖纸色与页边线，侧边目录可滚动。", "Warm paper, margin line, scrolling side tabs." },
            { "白底大标题，细线任务列表，界面最简洁。", "White, big title, hairline list. The simplest." },
            { "米色纸页与窄侧页签，更有手账感。", "Cream paper with narrow tabs, like a journal." },
            { "预览示意实际结构。切换保留各自当前页、内容与个性设置；输入法组合输入结束后应用。", "The previews show the real structure. Switching keeps each notebook's current page, content and settings; it applies once any IME input is finished." },
            { "布局提供默认风格；明确设置的字号、颜色与透明度优先，仍遵循全局／单组件设置。", "A layout sets the default look; font size, colors and opacity you set yourself still take priority, globally or per widget." },
            { "实时预览", "Live preview" },
            { "全局 · 所有跟随的组件", "Global · all widgets that follow it" },
            { "调整范围", "Apply to" },
            { "跟随全局外观", "Follow global appearance" },
            { "组件设置", "Widget" },
            { "浅色", "Light" },
            { "深色", "Dark" },
            { "主题", "Theme" },
            { "选择背景颜色", "Choose background color" },
            { "背景颜色", "Background" },
            { "不透明度（%）", "Opacity (%)" },
            { "字号（pt）", "Font size (pt)" },
            { "恢复此范围的默认外观", "Reset this appearance" },
            { "全部恢复默认外观", "Reset all appearance" },
            { "重置外观会保留所有课程、任务与历史页面。", "Resetting the appearance keeps all events, tasks and past pages." },
            { "设定学期节奏与桌面日历显示。下方统一管理整个课程系列，临时停课或调课可在日历中选择“仅这一次”。", "Set up the term and how the calendar looks. Manage whole series below; for a one-off change, choose \"Only this one\" in the calendar." },
            { "日历与学期默认值", "Calendar and term" },
            { "工作周（周一至周五）", "Work week (Mon–Fri)" },
            { "日历视图", "Calendar view" },
            { "星期一", "Monday" },
            { "星期日", "Sunday" },
            { "星期二", "Tuesday" },
            { "星期三", "Wednesday" },
            { "星期四", "Thursday" },
            { "星期五", "Friday" },
            { "星期六", "Saturday" },
            { "一周起始日", "Week starts on" },
            { "学期开始", "Term starts" },
            { "学期结束", "Term ends" },
            { "教学第 1 周起点", "Teaching week 1 starts" },
            { "日历会记住你上次在组件上选的视图，下次打开仍是它。", "The calendar remembers the view you last chose on the widget." },
            { "学期与教学周用于新增课程的默认循环范围；有效日期会自动保存。", "The term and teaching weeks set the default range for new recurring events; valid dates save automatically." },
            { "课程与循环系列", "Events and series" },
            { "课程名称", "Name" },
            { "日期 / 周期", "Date / repeat" },
            { "添加课程", "Add event" },
            { "编辑整个系列", "Edit series" },
            { "删除整个系列", "Delete series" },
            { "学期结束日期应晚于或等于开始日期；请调整日期后自动保存。", "The term must end on or after its start; adjust the dates and they will save automatically." },
            { "删除“{0}”整个系列及所有单次调整？", "Delete the whole \"{0}\" series and all its one-off changes?" },
            { "删除整个课程系列", "Delete series" },
            { "归档会将页面收进历史列表，内容与完成状态完整保留。归档页中的未完成任务仍然提醒。", "Archiving moves a page into the history list, keeping its content and progress. Unfinished tasks on archived pages still remind you." },
            { "便签与桌面页面", "Notebooks and pages" },
            { "选择便签", "Notebook" },
            { "保存名称", "Save name" },
            { "桌面当前页", "Page on the desktop" },
            { "全部页面 · 包含归档", "All pages · including archived" },
            { "状态", "Status" },
            { "创建日期", "Created" },
            { "重命名页面", "Rename page" },
            { "新建页面", "New page" },
            { "上移", "Up" },
            { "下移", "Down" },
            { "归档 / 取消归档", "Archive / unarchive" },
            { "显示在桌面", "Show on desktop" },
            { "选择页面以管理名称、顺序与归档状态。", "Choose a page to manage its name, order and archiving." },
            { "{0} 项任务 · {1} 项已完成", "{0} tasks · {1} done" },
            { "已归档，未完成任务继续提醒", "archived; unfinished tasks still remind you" },
            { "未归档", "not archived" },
            { "提醒会检查两本便签的所有页面，包括隐藏和归档页面。完成任务后停止后续提醒，错过的提醒会在恢复后汇总。", "Reminders check every page of both notebooks, hidden and archived ones included. They stop once a task is done; missed reminders are collected when the app runs again." },
            { "提醒方式", "Reminders" },
            { "默认提前（分钟）", "Default lead (minutes)" },
            { "只有日期的任务", "Date-only tasks" },
            { "当天这个时间提醒一次", "One reminder at this time that day" },
            { "启用免打扰时段", "Quiet hours" },
            { "免打扰", "Quiet hours" },
            { "开始 / 结束", "From / to" },
            { "播放提醒声音", "Play a sound" },
            { "声音", "Sound" },
            { "发送测试通知", "Send a test notification" },
            { "默认提前时间应用于新任务。免打扰结束后汇总待发提醒；测试通知可随时发送。", "The default lead time applies to new tasks. Reminders held during quiet hours are sent together afterwards; a test notification can be sent any time." },
            { "所有未完成的截止任务", "All unfinished tasks with a due time" },
            { "便签 / 页面", "Notebook / page" },
            { "此列表包含已到期或已提醒但尚未完成的任务。双击可打开所在页面。", "This list includes tasks that are due or already reminded but not done. Double-click to open the page." },
            { "所有数据仅保存在本机；只有填写了 Outlook 链接时，才会联网下载那一个日历。导入与恢复备份前，会先保留当前内容，便于回退。", "All data stays on this computer; DeskStudy only goes online to download your Outlook calendar, if you added its link. Before importing or restoring, the current data is kept so you can go back." },
            { "本地保存", "Saving" },
            { "即时 · 编辑后约 0.45 秒", "Instant · about 0.45 s after editing" },
            { "编辑后 1 秒", "1 s after editing" },
            { "编辑后 2.5 秒", "2.5 s after editing" },
            { "自动保存", "Autosave" },
            { "自动保存始终启用；退出时立即保存。", "Autosave is always on; everything is saved on exit." },
            { "导出全部数据…", "Export all data…" },
            { "导入数据…", "Import data…" },
            { "备份与恢复", "Backup and restore" },
            { "立即备份", "Back up now" },
            { "刷新列表", "Refresh" },
            { "备份文件", "Backup" },
            { "保存时间", "Saved" },
            { "恢复所选备份…", "Restore selected backup…" },
            { "恢复备份", "Restore backup" },
            { "恢复前将创建当前数据的安全备份。布局与外观重置不删除课程、任务或历史页面。", "A safety copy of the current data is made before restoring. Resetting the layout or appearance does not delete events, tasks or past pages." },
            { "已显示", "Shown" },
            { "已隐藏", "Hidden" },
            { " · 始终置顶", " · Always on top" },
            { " · 位置已锁定", " · Locked" },
            { "已停用", "Off" },
            { "尚未保存自定义布局。重置与找回不会影响内容。", "No layout saved yet. Resetting or bringing widgets back does not affect content." },
            { "已保存布局：{0}。重置与找回不会影响内容。", "Layout saved: {0}. Resetting or bringing widgets back does not affect content." },
            { "选择颜色", "Choose color" },
            { "正在调整全局外观，所有跟随全局的组件会同步变化。", "Changing the global appearance; all widgets that follow it change too." },
            { "此组件正在跟随全局。取消勾选后可以单独调整。", "This widget follows the global appearance. Untick to set it on its own." },
            { "此组件使用独立外观。勾选“跟随全局外观”即可恢复同步。", "This widget has its own appearance. Tick \"Follow global appearance\" to follow it again." },
            { "数据位置：{0}", "Data folder: {0}" },
            { "最近备份：尚无备份", "Last backup: none yet" },
            { "最近备份：{0}", "Last backup: {0}" },
            { "每周 · 至 {0}", "Weekly · until {0}" },
            { "每两周 · 至 {0}", "Every two weeks · until {0}" },
            { "已归档", "Archived" },
            { "使用中", "Active" },
            { "待提醒", "Upcoming" },
            { "临近截止", "Due soon" },
            { "已发送提醒", "Reminded" },
            { "检查截止时间", "Check due time" },
            { "（归档）", "(archived)" },
            { "登录 Windows 后自动启动", "Start when I sign in to Windows" },
            { "数据已恢复，但 Windows 未允许更新开机启动项。请检查权限后重新设置。", "The data was restored, but Windows did not allow updating the start-at-sign-in entry. Check permissions and set it again." },
            { "无法读取 Windows 开机启动项；此处显示已保存的偏好。", "Cannot read the Windows start-up entry; showing the saved preference." },
            { "通知测试。测试按钮不受应用免打扰时段限制，Windows 勿扰仍可能影响横幅。", "Test notification. The test ignores the app's quiet hours; Windows Do Not Disturb may still hide the banner." },
            { "Windows 未接受静音系统通知。提醒记录仍保留在提醒中心。", "Windows did not accept the silent notification. The reminder is still in the reminder center." },
            { "将恢复所选备份中的课表、便签、设置和布局。恢复前会先保留当前数据。\n\n", "The calendar, notebooks, settings and layout from the selected backup will be restored. The current data is kept first.\n\n" },
            { "桌面课笺", "DeskStudy" },
            { "保存失败", "Save failed" },
            { "保存中…", "Saving…" },
            { "已保存", "Saved" },
            { "桌面课笺 · 课表 / Todo / DDL", "DeskStudy · Calendar / To-do / Deadlines" },
            { "数据恢复", "Data recovery" },
            { "桌面课笺 · 已自动保存", "DeskStudy · Saved" },
            { "桌面课笺 · 保存失败，请导出备份", "DeskStudy · Save failed, please export a backup" },
            { "无法保存", "Cannot save" },
            { "本次保存失败，内容仍在内存中。请检查磁盘或从菜单导出备份。\n\n", "Saving failed; your content is still in memory. Check the disk or export a backup from the menu.\n\n" },
            { "恢复提醒 · {0} 项", "Missed reminders · {0}" },
            { "课笺提醒 · {0} 项", "Reminders · {0}" },
            { "另有 {0} 项，点击查看全部", "{0} more — click to see all" },
            { "桌面课笺 · 系统通知未发送，请查看提醒中心", "DeskStudy · Notification not sent, see the reminder center" },
            { "显示全部组件", "Show all widgets" },
            { "隐藏全部组件", "Hide all widgets" },
            { "显示 / 隐藏 {0}", "Show / hide {0}" },
            { "提醒中心", "Reminder center" },
            { "通知测试", "Test notification" },
            { "导出数据…", "Export data…" },
            { "使用说明", "Help" },
            { "保存并退出", "Save and exit" },
            { "课笺数据 (*.json)|*.json", "DeskStudy data (*.json)|*.json" },
            { "课笺备份-", "DeskStudy-backup-" },
            { "导出全部课表、便签和窗口设置", "Export the calendar, notebooks and window settings" },
            { "备份已导出。", "Backup exported." },
            { "导出完成", "Exported" },
            { "导出失败", "Export failed" },
            { "导入备份", "Import backup" },
            { "导入会替换当前课表、两本便签和窗口设置。当前数据将先保存为本地备份。是否继续？", "Importing replaces the current calendar, both notebooks and window settings. The current data is saved as a local backup first. Continue?" },
            { "备份已恢复。", "Backup restored." },
            { "\n\n导入前备份保留在本地数据目录。", "\n\nThe backup from before the import is kept in the data folder." },
            { "导入完成", "Imported" },
            { "导入或界面恢复失败", "Import or restore failed" },
            { "提醒中心 · 桌面课笺", "Reminder center · DeskStudy" },
            { "所有页面的提醒记录 · 错过的提醒会在恢复运行后汇总", "Reminders from every page · missed ones are collected when the app runs again" },
            { "来源", "From" },
            { "记录时间", "Logged" },
            { "补发 · ", "Catch-up · " },
            { "当天", "That day" },
            { "提前", "Before" },
            { "截止", "Due" },
            { "暂无提醒。可从组件菜单发送测试通知。", "No reminders yet. You can send a test notification from the menu." },
            { "应用无法继续运行。已保存的数据仍保留在本地。\n\n", "DeskStudy cannot continue. Your saved data is still on this computer.\n\n" },
            { "\n\n数据目录：", "\n\nData folder:" },
            { "桌面课笺 {0}\n\n桌面组件模式下，组件没有标题栏，各自不占任务栏（程序在任务栏上有一个「桌面课笺」按钮）：拖动顶栏移动，拖动边缘调整大小；松手后，靠近屏幕边缘或其他组件的会自动贴齐，稍微超出屏幕的会滑回，压住其他组件的会让开；点击组件时它浮到前面，切到别的程序后自动回到其他窗口下面。单击托盘图标或按快捷键（默认 Ctrl+Alt+Shift+D）可把组件浮到前面。可在设置中心的「显示与布局」切回标准窗口。\n\n外观页可切换五种便签布局。点击页标题可编辑，在任务末尾连续录入；点任务下方的状态文字可设置或修改截止时间。\n\n从托盘菜单或任一组件的齿轮按钮打开设置中心。关闭设置中心后，组件与提醒继续运行。\n\n显示与布局：管理置顶、位置锁定、保存布局；窗口移出屏幕后，可使用「找回当前屏幕」。外观支持全局设置和组件单独覆盖，修改立即预览并自动保存。\n\n日历：支持周/月视图和循环课表。临时停课或调课可选择「仅这一次」；设置中心可统一管理课程系列与学期。\n\n便签：文字和任务自动保存，设置中心可管理页面名称、顺序、归档和当前页。隐藏、翻页或归档不会取消未完成任务的提醒。\n\n提醒每 5 秒检查所有页面；免打扰结束、退出后重新运行或休眠恢复后汇总补发。完全退出后不能实时通知，请保留托盘运行。\n\n数据与应用：导入、导出、备份恢复和开机启动。恢复前会先保留当前数据。重置布局或外观不会删除内容。\n\n完整说明见程序文件夹里的「使用指南.html」。\n\n数据目录：\n", "DeskStudy {0}\n\nDesktop widgets have no title bar and no taskbar buttons of their own (DeskStudy has one taskbar button): drag the header to move, drag an edge to resize. When you let go, a widget snaps to a nearby screen edge or widget, slides back if it went slightly off screen, and moves aside if it covers another widget. Clicking a widget brings it to the front; switching to another program sends it back behind. Click the tray icon or press the shortcut (Ctrl+Alt+Shift+D by default) to bring the widgets forward. Standard windows can be turned back on under Settings > Display and layout.\n\nAppearance offers five notebook layouts. Click a page title to rename it, add tasks at the end of the list, and click the line under a task to set or change its due time. Double-click a task to edit its text.\n\nOpen Settings from the tray menu or any widget's gear button. Widgets and reminders keep running after you close Settings.\n\nDisplay & layout: pin, lock positions and save layouts; if a window is lost off screen, use \"Bring back to this screen\". Appearance can be set globally or per widget, previews right away and saves automatically.\n\nCalendar: week, work week and month views with recurring events. For a one-off cancellation or change choose \"Only this one\"; manage series and the term in Settings.\n\nNotebooks: notes and tasks save automatically; Settings manages page names, order, archiving and the current page. Hiding, turning pages or archiving does not cancel reminders for unfinished tasks.\n\nReminders check every page every 5 seconds; reminders missed during quiet hours, while the app was closed or while the computer slept are sent together later. Keep DeskStudy running in the tray to be reminded on time.\n\nData & app: import, export, backup, restore and start at sign-in. The current data is kept before restoring. Resetting the layout or appearance never deletes content.\n\nThe full guide is \"User Guide.html\" in the program folder.\n\nData folder:\n" },
            // DDL deadlines: sorting and the calendar.
            { "单击选择要查看的任务", "Click to choose a task" },
            { "（已归档）", " (archived)" },
            { "截止：{0}", "Due: {0}" },
            { "页面：{0}", "Page: {0}" },
            { "单击或双击：编辑任务", "Click or double-click to edit" },
            { "单击：在 DDL 便签中查看 · 双击：编辑", "Click to show in Deadlines · double-click to edit" },
            { "当天截止", "Due that day" },
            { "{0} 截止", "Due {0}" },
            { "在日历上显示 DDL 截止时间", "Show deadlines on the calendar" },
            { "DDL", "Deadlines" },
            { "DDL 按截止时间排序", "Sort deadlines by due time" },
            { "DDL 排序", "Deadline order" },
            { "{0} 项截止", "{0} due" },
            // Taskbar button.
            { "在任务栏显示「桌面课笺」图标", "Show a DeskStudy button on the taskbar" },
            { "任务栏", "Taskbar" },
            { "桌面组件模式下生效：单击任务栏图标把组件浮到前面，再单击一次收回去。右键图标选「固定到任务栏」，没运行时点它也能打开。", "In desktop mode: click the taskbar button to bring the widgets forward, click again to send them back. Right-click it and choose Pin to taskbar to start DeskStudy from there too." },
            // Outlook calendar.
            { "全天", "All day" },
            { "Outlook 日程（只读）", "Outlook event (read-only)" },
            { "来自 Outlook · 只读，请在 Outlook 中修改", "From Outlook · read-only, change it in Outlook" },
            { "这个链接返回的不是日历（ICS）文件。", "This link did not return a calendar (ICS) file." },
            { "日历文件太大（超过 30 MB）。", "The calendar file is too large (over 30 MB)." },
            { "找不到这个日历，可能已取消发布（{0}）。", "Calendar not found; it may no longer be published ({0})." },
            { "没有权限读取这个日历（{0}）。", "No permission to read this calendar ({0})." },
            { "服务器返回错误（{0}）。", "The server returned an error ({0})." },
            { "连接超时。", "The connection timed out." },
            { "无法连接网络。", "Cannot reach the network." },
            { "网络错误。", "Network error." },
            { "无法读取日历文件。", "The calendar file could not be read." },
            { "Outlook 日历（只读）", "Outlook calendar (read-only)" },
            { "ICS 链接", "ICS link" },
            { "保存并同步", "Save and sync" },
            { "Outlook 日历链接应以 https:// 开头，或是 webcal:// 链接。", "The Outlook calendar link must start with https:// or webcal://." },
            { "类别颜色", "Category colors" },
            { "在日历上显示 Outlook 日程", "Show Outlook events on the calendar" },
            { "显示", "Show" },
            { "每 {0} 分钟", "Every {0} min" },
            { "自动刷新", "Refresh" },
            { "日程开始前提醒", "Remind before events start" },
            { "分钟前", "min before" },
            { "获取链接：在 Outlook 网页版打开 设置 → 日历 → 共享日历 →「发布日历」，选择日历和「可查看所有详细信息」，点「发布」后复制 ICS 链接。拿到这个链接的人都能看到你的日程，请勿外传。", "To get the link: in Outlook on the web open Settings > Calendar > Shared calendars > Publish a calendar, choose the calendar and \"Can view all details\", select Publish and copy the ICS link. Anyone with this link can see your events, so keep it private." },
            { "同步后，这里会列出日历里用到的 Outlook 类别。", "After a sync, the Outlook categories in your calendar are listed here." },
            { "类别颜色：{0}", "Category color: {0}" },
            { "正在同步…", "Syncing…" },
            { "尚未订阅。粘贴链接后点「保存并同步」。", "Not subscribed. Paste the link and select Save and sync." },
            { "同步失败：{0}", "Sync failed: {0}" },
            { "仍显示上次同步的内容（{0}）。", "Still showing the last sync ({0})." },
            { "正在等待第一次同步…", "Waiting for the first sync…" },
            { "上次同步：{0} · 共 {1} 个日程", "Last sync: {0} · {1} events" },
            { "Outlook 日历设置无效。", "Invalid Outlook calendar settings." },
            { "Outlook 类别颜色无效。", "Invalid Outlook category colors." },
            // All-day events, Outlook colors and copying.
            { "更改这个日程的颜色…", "Change this event's color…" },
            { "关闭", "Close" },
            { "天", "days" },
            { "原来的颜色", "Original color" },
            { "结束时间须晚于开始时间；跨天日程请分成两条，或勾选「全天」。", "The end must be after the start; split an event across midnight in two, or tick All day." },
            { "全天日程的天数应在 1 到 366 之间。", "An all-day event lasts 1 to 366 days." },
            { "（无标题）", "(No title)" },
            { "日程颜色", "Event colors" },
            { "复制到本地并停止同步", "Copy to my calendar and stop syncing" },
            { "同步后，这里会列出日历里的每个日程，可以分别设颜色。", "After a sync, each event in the calendar is listed here and can have its own color." },
            { "日程颜色：{0}", "Event color: {0}" },
            { "还没有同步到 Outlook 日程，没有可复制的内容。", "No Outlook events have been synced yet, so there is nothing to copy." },
            { "复制到本地", "Copy to my calendar" },
            { "将把 Outlook 日历复制为本地日程：{0} 个循环课程、{1} 个单次日程，颜色保持不变。", "The Outlook calendar will be copied into your own calendar: {0} recurring and {1} single events, in the same colors." },
            { "之后停止同步，也不再显示 Outlook 日历；复制来的日程可以像自己的课程一样修改。复制前会自动备份，可在「数据与应用」中恢复。", "Syncing then stops and the Outlook calendar is no longer shown; the copies can be edited like your own events. A backup is made first; restore it under Data and app if needed." },
            { "只复制已同步的范围（今天前 {0} 天到今后 {1} 天）。", "Only the synced range is copied ({0} days back to {1} days ahead)." },
            { "已复制 {0} 个日程到本地日历，Outlook 同步已停止。", "{0} events copied into your calendar. Outlook syncing has stopped." },
            { "Outlook 日程颜色无效。", "Invalid Outlook event colors." },
            { "同「{0}」", "Same as \"{0}\"" },
            { "自定义颜色…", "Custom color…" },
            { "自定义 {0}", "Custom {0}" },
        };
    }
}
